import {CubeTexture, Texture} from "three";
import FBX from "@/app/_types/FBX";
import {
    Enamel,
    Finish,
    JewelTypes,
    Materials, Paves, Preciousness,
    Prices,
    SignatureTeeth,
    SignMaterial,
    SignVisibility,
    Stones, Visibility, History, Neighbours, HistoryPack, Packaging
} from "@/app/_types/TeethOptions";

interface TempPrices {
    base: any[],
    bezel: {
        [key: string]: any[],
        whDLab_b: any[],
        whDNat_b: any[],
        brDLab_b: any[],
        brDNat_b: any[],
        blDLab_b: any[],
        blDNat_b: any[],
        ruby_b: any[],
        emerald_b: any[],
        ameth_b: any[],
        aqua_b: any[],
        bSapph_b: any[],
        ySapph_b: any[],
        pSapph_b: any[],
    },
    pave: {
        [key: string]: any[],
        whDLab_p: any[],
        whDNat_p: any[],
        brDLab_p: any[],
        brDNat_p: any[],
        blDLab_p: any[],
        blDNat_p: any[],
        ruby_p: any[],
        emerald_p: any[],
        ameth_p: any[],
        aqua_p: any[],
        bSapph_p: any[],
        ySapph_p: any[],
        pSapph_p: any[],
        camo_p: any[],
        glitch_p: any[],
    },
    finish: any[],
    signature: any[]
}

export interface State {
    envMap: Texture | CubeTexture | undefined,
    hovered: string|undefined,
    teethGeometry: FBX,
    teethMaterial: Materials,
    teethJewelType: JewelTypes,
    teethStones: Stones,
    teethVisibility: Visibility,
    teethPrices: Prices,
    teethFinish: Finish,
    signatureMaterial: SignMaterial,
    signatureVisibility: SignVisibility,
    teethSignature: SignatureTeeth,
    teethNeighboursInt: Neighbours,
    teethNeighboursEst: Neighbours,
    history: History[][],
    currentHistory: number,
    historyPack: HistoryPack[][],
    currentHistoryPack: number,
    currentTooth: string | undefined,
    lastActivatedTooth: string | undefined,
    teethEnamel: Enamel,
    teethPaves: Paves,
    activeButton: string|undefined,
    activeSubButton: string|undefined,
    showGemTypeBox: boolean,
    setShowGemTypeBox: (value:boolean) => void,
    loaded: boolean,
    prices: TempPrices | undefined | null,
    total: number,
    isScreenshotNeeded: boolean | undefined,
    resetControls: boolean | undefined,
    recap: boolean,
    teethPreciousness: Preciousness,
    nextStep: boolean,
    setNextStep: (bool: boolean) => void,
    setRecap: (bool:boolean) => void,
    setActiveButton: (button:string|undefined) => void,
    setActiveSubButton: (button:string|undefined) => void,
    setIsScreenshotNeeded: (value:boolean|undefined) => void,
    setResetControls: (value:boolean|undefined) => void,
    setEnvMap: (em: Texture | CubeTexture) => void,
    setHover: (tooth: string|undefined) => void,
    setGeometry: (fbx:FBX) => void,
    setMaterial: (tooth:string, color:string) => void,
    setType: (tooth:string, type:string) => void,
    setPave: (tooth:string, pave:string, color:string|undefined) => void,
    setStone: (tooth:string, shape:string, color:string) => void,
    setEnamel: (tooth:string, color:string) => void,
    setActiveTooth: (tooth:string|undefined) => void,
    setSignature: (signature:string, material:string, mainMenu:boolean) => void,
    setTeethPreciousness: (carats:number, diamonds:string|undefined) => void,
    unsetLastActivatedTooth: () => void,
    resetTooth: (tooth:string) => void,
    setLoaded: (bool:boolean) => void,
    fetchPrices: () => void,
    undo: () => void,
    redo: () => void,
    undoPack: () => void,
    redoPack: () => void,
    resetHistoryStep: (state:State) => void,
    resetHistoryPackStep: (state:State) => void,
    resetSignature: (signature: string) => void,
    reset: () => void,
    resetPack: () => void,
    calcTotal: (state:State) => void,
    setHistory: (state:State) => void,
    setHistoryPack: (state:State) => void,
    resetList: (state:State, tooth:string) => void,
    checkDiamonds: (state: State) => boolean,
    packagingScene: boolean,
    packaging: Packaging,
    setPackaging: (prop:string, value:string|boolean) => void
}