import {CubeTexture, Texture} from "three";
import FBX from "@/app/_types/FBX";
import {
    Enamel,
    Finish,
    JewelTypes,
    Materials, Paves, Preciousness,
    Prices,
    SignatureTeeth,
    SignMaterial,
    SignVisibility,
    Stones, Visibility, History
} from "@/app/_types/TeethOptions";

export interface State {
    envMap: Texture | CubeTexture | undefined,
    hovered: string|undefined,
    teethGeometry: FBX,
    teethMaterial: Materials,
    teethJewelType: JewelTypes,
    teethStones: Stones,
    teethVisibility: Visibility,
    teethPrices: Prices,
    teethFinish: Finish,
    signatureMaterial: SignMaterial,
    signatureVisibility: SignVisibility,
    teethSignature: SignatureTeeth,
    history: History[][],
    currentHistory: number,
    currentTooth: string | undefined,
    lastActivatedTooth: string | undefined,
    teethEnamel: Enamel,
    teethPaves: Paves,
    activeButton: string|undefined,
    activeSubButton: string|undefined,
    loaded: boolean,
    prices: any[] | undefined | null,
    total: number,
    isScreenshotNeeded: boolean | undefined,
    resetControls: boolean | undefined,
    recap: boolean,
    teethPreciousness: Preciousness,
    nextStep: boolean,
    setNextStep: (bool: boolean) => void,
    setRecap: (bool:boolean) => void,
    setActiveButton: (button:string|undefined) => void,
    setActiveSubButton: (button:string|undefined) => void,
    setIsScreenshotNeeded: (value:boolean|undefined) => void,
    setResetControls: (value:boolean|undefined) => void,
    setEnvMap: (em: Texture | CubeTexture) => void,
    setHover: (tooth: string|undefined) => void,
    setGeometry: (fbx:FBX) => void,
    setMaterial: (tooth:string, color:string) => void,
    setType: (tooth:string, type:string) => void,
    setPave: (tooth:string, pave:string, color:string|undefined) => void,
    setStone: (tooth:string, shape:string, color:string) => void,
    setEnamel: (tooth:string, color:string) => void,
    setActiveTooth: (tooth:string|undefined) => void,
    setSignature: (signature:string, material:string, mainMenu:boolean) => void,
    setTeethPreciousness: (carats:number, diamonds:string|undefined) => void,
    unsetLastActivatedTooth: () => void,
    resetTooth: (tooth:string) => void,
    setLoaded: (bool:boolean) => void,
    fetchPrices: () => void,
    undo: () => void,
    redo: () => void,
    resetHistoryStep: (state:State) => void,
    resetSignature: (signature: string) => void,
    reset: () => void,
    calcTotal: (state:State) => void,
    setHistory: (state:State) => void,
    resetList: (state:State, tooth:string) => void
    checkDiamonds: (state: State) => boolean;
}