import {CubeTexture, Texture} from "three";
import FBX from "@/app/_types/FBX";
import {
    Enamel,
    Finish,
    JewelTypes,
    Materials, Paves, Preciousness,
    Prices,
    SignatureTeeth,
    SignMaterial,
    SignVisibility,
    Stones, Visibility, History, Neighbours, HistoryPack, Packaging, Design
} from "@/app/_types/TeethOptions";

export interface TempPrices {
    base: any[],
    bezel: {
        [key: string]: any[],
        whDLab_b: any[],
        whDNat_b: any[],
        blDNat_b: any[],
        stone_b: any[],
    },
    pave: {
        [key: string]: any[],
        whDLab_p: any[],
        whDNat_p: any[],
        brDNat_p: any[],
        blDNat_p: any[],
        stone_p: any[],
        camo_p: any[],
        glitch_p: any[],
    },
    signature: any[]
}

export interface State {
    bufferConfigImage: string | undefined,
    setBufferConfigImage: (buffer:string) => void,
    scanImage: { scan: ArrayBuffer|undefined, type: string | undefined, name: string | undefined },
    setScanImage: (scan:ArrayBuffer, type:string | undefined, name:string) => void,
    savedConfig: number|undefined,
    setSavedConfig: (id:number|undefined) => void,
    isTouch: boolean,
    setIsTouch: (bool:boolean) => void,
    envMap: Texture | CubeTexture | undefined,
    hovered: string|undefined,
    teethGeometry: FBX,
    teethMaterial: Materials,
    teethJewelType: JewelTypes,
    teethStones: Stones,
    teethVisibility: Visibility,
    teethPrices: Prices,
    teethFinish: Finish,
    signatureMaterial: SignMaterial,
    signatureVisibility: SignVisibility,
    teethSignature: SignatureTeeth,
    teethNeighboursInt: Neighbours,
    teethNeighboursEst: Neighbours,
    history: History[][],
    currentHistory: number,
    historyPack: HistoryPack[][],
    currentHistoryPack: number,
    currentTooth: string | undefined,
    lastActivatedTooth: string | undefined,
    teethEnamel: Enamel,
    teethPaves: Paves,
    activeButton: string|undefined,
    activeSubButton: string|undefined,
    showGemTypeBox: boolean,
    setShowGemTypeBox: (value:boolean) => void,
    loaded: boolean,
    prices: TempPrices | undefined | null,
    setPrices: (prices:any) => void,
    total: number,
    isScreenshotNeeded: boolean | undefined,
    resetControls: boolean | undefined,
    recap: boolean,
    teethPreciousness: Preciousness,
    nextStep: boolean,
    setNextStep: (bool: boolean) => void,
    setPackagingScene: (bool: boolean) => void,
    setRecap: (bool:boolean) => void,
    setActiveButton: (button:string|undefined) => void,
    setActiveSubButton: (button:string|undefined) => void,
    setIsScreenshotNeeded: (value:boolean|undefined) => void,
    setResetControls: (value:boolean|undefined) => void,
    setEnvMap: (em: Texture | CubeTexture) => void,
    setHover: (tooth: string|undefined) => void,
    setGeometry: (fbx:FBX) => void,
    setMaterial: (tooth:string, color:string) => void,
    setType: (tooth:string, type:Design) => void,
    setPave: (tooth:string, pave:string, color:string|undefined) => void,
    setStone: (tooth:string, shape:string, color:string) => void,
    setEnamel: (tooth:string, color:string) => void,
    setActiveTooth: (tooth:string|undefined) => void,
    setSignature: (signature:string, material:string, mainMenu:boolean) => void,
    setTeethPreciousness: (carats:number) => void,
    unsetLastActivatedTooth: () => void,
    resetTooth: (tooth:string) => void,
    setLoaded: (bool:boolean) => void,
    undo: () => void,
    redo: () => void,
    undoPack: () => void,
    redoPack: () => void,
    resetHistoryStep: (state:State) => void,
    resetHistoryPackStep: (state:State) => void,
    resetSignature: (signature: string) => void,
    reset: () => void,
    resetPack: (hard:boolean) => void,
    calcTotal: (state:State) => void,
    setHistory: (state:State) => void,
    setHistoryPack: (state:State) => void,
    resetList: (state:State, tooth:string) => void,
    packagingScene: boolean,
    packaging: Packaging | undefined,
    setPackaging: (prop:string, value:string|boolean, line?:number|undefined) => void,
    innerWidth: number,
    setInnerWidth: (width:number) => void,
    innerHeight: number,
    setInnerHeight: (height:number) => void,
    resetBigBar: (state: State, tooth: string) => void,
    resetNeighbours: (state:State, type:Design, tooth:string) => void,
    resetSameDiamondDesign: (state:State, type:Design, tooth:string) => boolean
    changeDiamondDesign: (state:State, type:Design, tooth:string) => boolean,
    changeDiamondDesignBB: (state:State, type:Design, tooth:string) => boolean,
    manageBigBar: (state:State, type:Design, tooth:string) => void,
    manageCentralBar: (state:State, type:Design, tooth:string) => void,
    managePreviousBigBar: (state:State, type:Design, tooth:string) => void
    managePreviousCentralBar: (state:State, type:Design, tooth:string) => void,
    manageDefault: (state:State, type:Design, tooth:string) => void
}
