'use client'
import {Modal} from "@mui/material";
import {Close} from "@/app/_components/_icons/Close";

export default function PrivacyPolicy({open, setClose}: {open: boolean, setClose: () => void}) {
    return (
        <Modal
            open={open}
            onClose={setClose}
            aria-labelledby="privacy-policy-title"
            aria-describedby="privacy-policy-description"
        >
            <div className="absolute top-1/2 left-1/2 max-h-[84dvh] w-[92%] max-w-4xl -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-3xl border border-stone-200 bg-gray-50 shadow-[0_24px_80px_rgba(0,0,0,0.18)]">
                <div className="flex items-start justify-between gap-4 border-b border-stone-200 bg-gray-50/95 px-5 py-5 backdrop-blur-sm lg:px-8">
                    <div className="pr-2">
                        <p className="text-xs font-medium uppercase tracking-[0.22em] text-stone-500">Legal</p>
                        <h1 id="privacy-policy-title" className="mt-2 text-2xl font-semibold text-stone-950 lg:text-3xl">
                            Privacy Policy
                        </h1>
                        <p id="privacy-policy-description" className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 lg:text-base">
                            This policy explains how DARKAI collects, uses, stores, and protects your personal data.
                        </p>
                    </div>
                    <button
                        type="button"
                        onClick={setClose}
                        aria-label="Close privacy policy"
                        className="shrink-0 cursor-pointer rounded-full border border-stone-200 bg-white p-1.5 transition hover:border-stone-300 hover:bg-stone-100"
                    >
                        <Close className="h-8 w-8"/>
                    </button>
                </div>

                <article className="max-h-[calc(84dvh-132px)] overflow-y-auto px-5 py-6 lg:px-8 lg:py-8 [&_h2]:mt-8 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:tracking-[0.01em] [&_h2]:text-stone-950 [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-stone-900 [&_p]:mt-3 [&_p]:text-sm [&_p]:leading-7 [&_p]:text-stone-700 [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6 [&_ul]:text-sm [&_ul]:leading-7 [&_ul]:text-stone-700 lg:[&_h2]:text-xl lg:[&_h3]:text-lg lg:[&_p]:text-[15px] lg:[&_ul]:text-[15px]">
                    <p>
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
                        of Your information when You use the Service and tells You about Your privacy rights and how
                        the law protects You.
                    </p>
                    <p>
                        We use Your Personal Data to provide and improve the Service. By using the Service, You agree
                        to the collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h2>PREFIX</h2>

                    <h3>Interpretation</h3>
                    <p>
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.
                    </p>

                    <h3>Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul>
                        <li>"Account" means a unique account created for You to access our Service or parts of our Service.</li>
                        <li>"Company" refers to DARKAI - ZCC S.R.L., Via Pra Bordoni 65, 36010 Zane (VI), Italy.</li>
                        <li>"Cookies" are small files placed on your computer, mobile device or other device by a website, containing details of your browsing history.</li>
                        <li>"Country" refers to: Italy.</li>
                        <li>"Device" means any device that can access the Service such as a computer, cellphone or digital tablet.</li>
                        <li>"Personal Data" is any information that relates to an identified or identifiable individual.</li>
                        <li>"Service" refers to the Website.</li>
                        <li>"Service Provider" means any natural or legal person who processes data on behalf of the Company.</li>
                        <li>"Usage Data" refers to data collected automatically, either generated by use of the Service or from the Service infrastructure itself.</li>
                        <li>"Website" refers to DARKAI, accessible from https://www.darkai-lab.com.</li>
                        <li>"You" means the individual or legal entity accessing or using the Service, as applicable.</li>
                    </ul>

                    <h2>SECTION 1 - TYPES OF DATA COLLECTED</h2>

                    <h3>Personal Data</h3>
                    <p>
                        While using Our Service, We may ask You to provide Us with certain personally identifiable
                        information that can be used to contact or identify You. Personally identifiable information may
                        include, but is not limited to:
                    </p>
                    <ul>
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Usage Data</li>
                    </ul>

                    <h3>Usage Data</h3>
                    <p>Usage Data is collected automatically when using the Service.</p>
                    <p>
                        Usage Data may include information such as Your Device&apos;s Internet Protocol address, browser
                        type, browser version, the pages of our Service that You visit, the time and date of Your
                        visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    </p>
                    <p>
                        When You access the Service by or through a mobile device, We may collect certain
                        information automatically, including the type of mobile device You use, Your mobile device
                        unique ID, the IP address of Your mobile device, Your mobile operating system, the type of
                        mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    </p>
                    <p>
                        We may also collect information that Your browser sends whenever You visit our Service or
                        when You access the Service by or through a mobile device.
                    </p>

                    <h2>SECTION 2 - TRACKING TECHNOLOGY &amp; COOKIES</h2>
                    <p>
                        We use Cookies and similar tracking technologies to track the activity on Our Service and store
                        certain information. Tracking technologies used are beacons, tags, and scripts to collect and
                        track information and to improve and analyze Our Service.
                    </p>
                    <p>The technologies We use may include:</p>
                    <ul>
                        <li>
                            "Cookies" or browser cookies. A cookie is a small file placed on Your Device. You can
                            instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.
                            However, if You do not accept Cookies, You may not be able to use some parts of our
                            Service.
                        </li>
                        <li>
                            "Web Beacons". Certain sections of our Service and our emails may contain small
                            electronic files known as web beacons, clear gifs, pixel tags, or single-pixel gifs.
                        </li>
                    </ul>
                    <p>
                        Cookies can be "Persistent" or "Session" cookies. Persistent Cookies remain on Your device
                        when You go offline, while Session Cookies are deleted as soon as You close Your browser.
                    </p>
                    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

                    <h3>Necessary/Essential Cookies</h3>
                    <p>Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p>
                        Purpose: These Cookies are essential to provide You with services available through the
                        Website and to enable You to use some of its features.
                    </p>

                    <h3>Cookies Policy/Notice Acceptance Cookies</h3>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>

                    <h3>Functionality Cookies</h3>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>
                        Purpose: These Cookies allow us to remember choices You make when You use the Website,
                        such as remembering login details or language preference.
                    </p>
                    <p>
                        For more information about the cookies we use and your choices regarding cookies, please
                        visit our Cookies Policy or the Cookies section of our Privacy Policy.
                    </p>

                    <h2>SECTION 3 - USE OF YOUR PERSONAL DATA</h2>
                    <p>The Company may use Personal Data for the following purposes:</p>
                    <ul>
                        <li>To provide and maintain our Service, including monitoring the usage of our Service.</li>
                        <li>To manage Your Account and Your registration as a user of the Service.</li>
                        <li>For the performance of a contract related to products, items or services purchased through the Service.</li>
                        <li>To contact You by email, telephone calls, SMS, push notifications or similar communications.</li>
                        <li>To provide You with news, special offers and general information about similar goods, services and events, unless You opt out.</li>
                        <li>To manage Your requests.</li>
                        <li>For business transfers such as mergers, divestitures, restructuring, reorganization, dissolution or other sale/transfer of assets.</li>
                        <li>For other purposes such as data analysis, usage trends, campaign effectiveness, and improvement of our Service, products and marketing.</li>
                    </ul>
                    <p>We may share Your personal information in the following situations:</p>
                    <ul>
                        <li>With Service Providers to monitor and analyze the use of our Service, or to contact You.</li>
                        <li>For business transfers in connection with merger, sale of assets, financing or acquisition.</li>
                        <li>With Affiliates, who will be required to honor this Privacy Policy.</li>
                        <li>With business partners to offer certain products, services or promotions.</li>
                        <li>With other users when You share information in public areas.</li>
                        <li>With Your consent for any other purpose.</li>
                    </ul>

                    <h2>SECTION 4 - RETENTION OF YOUR PERSONAL DATA</h2>
                    <p>
                        The Company will retain Your Personal Data only for as long as is necessary for the purposes
                        set out in this Privacy Policy. We will retain and use Your Personal Data to the extent
                        necessary to comply with legal obligations, resolve disputes, and enforce legal agreements
                        and policies.
                    </p>
                    <p>
                        The Company will also retain Usage Data for internal analysis purposes. Usage Data is
                        generally retained for a shorter period of time, except when used to strengthen security,
                        improve functionality, or where law requires longer retention.
                    </p>

                    <h2>SECTION 5 - TRANSFER YOUR PERSONAL DATA</h2>
                    <p>
                        Your information, including Personal Data, is processed at the Company&apos;s operating offices
                        and in any other places where the parties involved in the processing are located. This means
                        information may be transferred to and maintained on computers located outside of Your state,
                        province, country or other governmental jurisdiction where data protection laws may differ.
                    </p>
                    <p>
                        Your consent to this Privacy Policy followed by Your submission of such information represents
                        Your agreement to that transfer.
                    </p>
                    <p>
                        The Company will take all steps reasonably necessary to ensure that Your data is treated
                        securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will
                        take place unless there are adequate controls in place.
                    </p>

                    <h2>SECTION 6 - DELETE YOUR PERSONAL DATA</h2>
                    <p>
                        You have the right to delete or request that We assist in deleting the Personal Data that We
                        have collected about You.
                    </p>
                    <p>
                        Our Service may give You the ability to delete certain information from within the Service. You
                        may update, amend, or delete Your information at any time by signing in to Your Account, if
                        You have one, and visiting the account settings section that allows You to manage Your
                        personal information.
                    </p>
                    <p>
                        You may also contact Us to request access to, correct, or delete personal information that You
                        have provided to Us. We may retain certain information when we have a legal obligation or
                        lawful basis to do so.
                    </p>

                    <h2>SECTION 7 - DISCLOSURE OF YOUR PERSONAL DATA</h2>

                    <h3>Business Transactions</h3>
                    <p>
                        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
                        transferred. We will provide notice before Your Personal Data is transferred and becomes
                        subject to a different Privacy Policy.
                    </p>

                    <h3>Law Enforcement</h3>
                    <p>
                        Under certain circumstances, the Company may be required to disclose Your Personal Data if
                        required to do so by law or in response to valid requests by public authorities.
                    </p>

                    <h3>Other Legal Requirements</h3>
                    <p>
                        The Company may disclose Your Personal Data in the good faith belief that such action is
                        necessary to:
                    </p>
                    <ul>
                        <li>Comply with a legal obligation.</li>
                        <li>Protect and defend the rights or property of the Company.</li>
                        <li>Prevent or investigate possible wrongdoing in connection with the Service.</li>
                        <li>Protect the personal safety of Users of the Service or the public.</li>
                        <li>Protect against legal liability.</li>
                    </ul>

                    <h3>Security of Your Personal Data</h3>
                    <p>
                        The security of Your Personal Data is important to Us, but no method of transmission over the
                        Internet or method of electronic storage is 100% secure. While We strive to use commercially
                        acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                    </p>

                    <h2>SECTION 8 - CHILDREN&apos;S PRIVACY</h2>
                    <p>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect
                        personally identifiable information from anyone under the age of 13.
                    </p>
                    <p>
                        If You are a parent or guardian and You are aware that Your child has provided Us with
                        Personal Data, please contact Us. If We become aware that We have collected Personal Data
                        from anyone under the age of 13 without verification of parental consent, We take steps to
                        remove that information from Our servers.
                    </p>
                    <p>
                        If We need to rely on consent as a legal basis for processing Your information and Your
                        country requires consent from a parent, We may require Your parent&apos;s consent before We
                        collect and use that information.
                    </p>

                    <h2>SECTION 9 - LINKS TO OTHER WEBSITES</h2>
                    <p>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a
                        third party link, You will be directed to that third party&apos;s site. We strongly advise You to
                        review the Privacy Policy of every site You visit.
                    </p>
                    <p>
                        We have no control over and assume no responsibility for the content, privacy policies or
                        practices of any third party sites or services.
                    </p>

                    <h2>SECTION 10 - CHANGES TO THIS PRIVACY POLICY</h2>
                    <p>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by
                        posting the new Privacy Policy on this page.
                    </p>
                    <p>
                        We will let You know via email and/or a prominent notice on Our Service prior to the change
                        becoming effective, and update the "Last updated" date at the top of this Privacy Policy.
                    </p>
                    <p>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this
                        Privacy Policy are effective when they are posted on this page.
                    </p>

                    <h2>SECTION 11 - CONTACT INFORMATION</h2>
                    <p>
                        If you have any questions about this Privacy Policy, You can contact us by email at
                        support@darkai-lab.com.
                    </p>
                </article>
            </div>
        </Modal>
    )
}
